[package]
name = "smol-potat"
version = "0.1.0"
authors = ["Daniel Eades <danieleades@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    ".", "smol-potat-macro"
]

[dependencies]
smol-potat-macro = {path = "smol-potat-macro"}
num_cpus = { version = "1.13.0", optional = true }
smol = "0.1.5"

[features]
auto = ["smol-potat-macro/auto", "num_cpus"]