[package]
name = "smol-potat"
description = "Proc macro for smol runtime."
license = "MIT OR Apache-2.0"
version = "0.2.1"
authors = ["YuWeiWu <wusyong9104@gmail.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/wusyong/smol-potat"
homepage = "https://github.com/wusyong/smol-potat"
documentation = "https://docs.rs/smol-potat"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    ".", "smol-potat-macro"
]

[dependencies]
smol-potat-macro = {path = "smol-potat-macro"}
num_cpus = { version = "1.13.0", optional = true }
smol = "0.1.5"

[features]
auto = ["smol-potat-macro/auto", "num_cpus"]