[package]
name = "smol-attributes"
description = "Experimental language-level polyfills for Async Rust."
license = "MIT OR Apache-2.0"
version = "0.1.0"
authors = ["YuWeiWu <wusyong9104@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = ["full"] }
quote = "1.0"
smol = "0.0.1"